### ISSUE TITLE
Update exercises for AS3.0

### ISSUE THREAD

**Issue by gregoriopalama** [udacity/ud851-Sunshine#108]
This is not a major issue, just a minor one since AS 3.0 will update the projects when you add them, but it would be nice if the projects were already updated for the usage with the latest stable release of AS. For example, dependencies are old, there is not the new maven repo and build tools are not updated.

**Comment by sri-new** [comment]
I am with @gregoriopalama on this one. Please update the gradle build scripts. People accessing this repository come from diverse backgrounds. I have seen people with multiple versions of the same library, naturally, running into errors and being unable to proceed to the next lesson. I even attempted to fix this but the contributing section clearly states that PRs are not possible with this repo. 

Hopefully, this issue doesn't get superseded by another.

**Comment by johnshea** [comment]
Resolved. Dependencies have been updated.
