### ISSUE TITLE
Missing TODOs in S02.03

### ISSUE THREAD

**Issue by gabor-meszaros** [udacity/ud851-Sunshine#11]
In S02.03's TODO (7) and TODO (17) we need to find the error display text view and the loading indicator progress bar by ID. However, we did not set any ID in the [activity_forecast.xml](https://github.com/udacity/ud851-Sunshine/blob/student/S02.03-Exercise-Polish/app/src/main/res/layout/activity_forecast.xml) (e.g. after TODO (5) & TODO (15)). It may be intended (we should solve this ourselves), but we have always had an explicit step for it earlier.

**Comment by JeremySilverTongue** [comment]
Yeah I think this is intended. As we go through the course the TODOs become less step-by-step, and assume you can handle things like assigning ids and so forth.
