### ISSUE TITLE
more performance to code is it true?

### ISSUE THREAD

**Issue by issac-nabil** [udacity/ud851-Sunshine#113]
```
      for (String dummyWeatherDay : dummyWeatherData) {
            mWeatherTextView.append(dummyWeatherDay + "\n\n\n");
        }
```

     #  i thinks better to do this

 ```
StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i>= weather_temp.length; i++){
            stringBuilder.append(i);
            stringBuilder.append("\n");
        }
 tv_weather_data.setText(stringBuilder);

```

**Comment by mamuleanu** [comment]
> i thinks better to do this

> ```
> StringBuilder stringBuilder = new StringBuilder();
>        for (int i = 0; i>= weather_temp.length; i++){
>            stringBuilder.append(i);
>            stringBuilder.append("\n");
>        }
> tv_weather_data.setText(stringBuilder);
> ```

From what I understand you are referring to S01.02-Solution-AddWeatherList project. The correct version of the code you've written should be: 

```
StringBuilder sb = new StringBuilder();
for(int i = 0; i < dummyWeatherData.length;i++){
    sb.append(dummyWeatherData[i]);
    sb.append("\n");
}
mWeatherTextView.append(sb);
```
However, in this case, since the `dummyWeatherData` array is not large I think the best is to use the `foreach` version presented in the solution project. Also, using the `foreach` keeps the code clean and easy to read for all students.

**Comment by issac-nabil** [comment]
yea this code from my last exp
`StringBuilder stringBuilder = new StringBuilder();
       for (int i = 0; i>= weather_temp.length; i++){
           stringBuilder.append(i);
           stringBuilder.append("\n");
       }
tv_weather_data.setText(stringBuilder);`

and this in lesson already 
`for (String dummyWeatherDay : dummyWeatherData) {
            mWeatherTextView.append(dummyWeatherDay + "\n\n\n");
        }`

thanks mamuleanu
