### ISSUE TITLE
S09.04 Todo position to split

### ISSUE THREAD

**Issue by JonathanImperato** [udacity/ud851-Sunshine#119]
In S09.04, there is a todo that in my opinion should come later than its currently position.
 I am talking about the [todo n19](https://github.com/udacity/ud851-Sunshine/blob/S09.04-Solution-UsingCursorLoader/app/src/main/java/com/example/android/sunshine/MainActivity.java#L161) that call the method showLoading(); that won't be created until the [todo n34](https://github.com/udacity/ud851-Sunshine/blob/S09.04-Solution-UsingCursorLoader/app/src/main/java/com/example/android/sunshine/MainActivity.java#L323).

**Comment by jwill** [comment]
Thanks for your input. We'll be leaving it as is for the time being.
