### ISSUE TITLE
S03.02  Grade build errors- Failed to crunch file

### ISSUE THREAD

**Issue by bloggi85** [udacity/ud851-Sunshine#12]
Hello

I arrived at S03.02 but for some reason I am getting the following build error (in the solution project):

`Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:compileDebugSources, :app:compileDebugAndroidTestSources, :app:compileDebugUnitTestSources]
Error:Failed to crunch file C:\Users\Laurent\Sunshine\ud851-Sunshine-student\S03.02-Solution-RecyclerViewClickHandling\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png into C:\Users\Laurent\Sunshine\ud851-Sunshine-student\S03.02-Solution-RecyclerViewClickHandling\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: Failed to crunch file C:\Users\Laurent\Sunshine\ud851-Sunshine-student\S03.02-Solution-RecyclerViewClickHandling\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.1.0\res\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png into C:\Users\Laurent\Sunshine\ud851-Sunshine-student\S03.02-Solution-RecyclerViewClickHandling\app\build\intermediates\res\merged\debug\drawable-hdpi-v4\abc_ic_menu_share_mtrl_alpha.png
Information:BUILD FAILED
Information:Total time: 1.4 secs`

I've tried following advise on StackOverflow, Clean Project and re-cloning from GitHub, but none of them seem to help. 

Has anybody else come across this problem by any chance?

Thanks

**Comment by aleperf** [comment]
I had a similar problem, in my  case the path to the file Android was unable to load was too long, the solution was to rename the folder containing all the code to something shorter, instead of "ud851...-etc", I renamed it to something shorter.
Look also at this: 
http://stackoverflow.com/questions/30764604/execution-failed-for-task-appmergedebugresources-crunching-cruncher-png-fa

**Comment by bloggi85** [comment]
Thanks @aleperf  that fixed it! I made the path a bit shorter by renaming "ud851-Sunshine-student" to "Sunshine" and moved that folder to my C drive, and then it magically worked.
