### ISSUE TITLE
bug in sunshine app (S09.04)

### ISSUE THREAD

**Issue by codingworkshopru** [udacity/ud851-Sunshine#13]
https://github.com/udacity/ud851-Sunshine/blob/S09.04-Exercise-UsingCursorLoader/app/src/main/java/com/example/android/sunshine/DetailActivity.java#L82

it should be
```java
inflater.inflate(R.menu.detail, menu);
```

**Comment by JeremySilverTongue** [comment]
Good catch! Fixed :D
