### ISSUE TITLE
zip file of repositories are notable to download

### ISSUE THREAD

**Issue by asadansari219** [udacity/ud851-Sunshine#131]
I am trying to download sunshine code and toy app repository but its not download. It's saying "not able to download" or "server not responding".

**Comment by linibensonjr** [comment]
How about you try cloning the repo, that may probably help

**Comment by ibnahmadbello** [comment]
The same issue was happening with me. But I got over it by cloning the repo.

**Comment by johnshea** [comment]
I tried and was able to download without problems. Please try again. If it is still happening, please provide the steps you are doing and screenshots so we can troubleshoot it. Thank you.
