### ISSUE TITLE
 ud851-Sunshine/S10.03-Exercise-FirebaseJobDispatcher/app/build.gradle

### ISSUE THREAD

**Issue by calincan2000** [udacity/ud851-Sunshine#132]
At  ud851-Sunshine/S10.03-Exercise-FirebaseJobDispatcher/app/build.gradle
please change the following to version 25.1.0

    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.android.support:preference-v7:25.0.1'

It’s advised that we use the same version for all support libraries.
compile 'com.android.support:appcompat-v7:25.1.0'

Here we are using 25.1.0 so make sense we change others to the same version

**Comment by johnshea** [comment]
Fixed. All have been updated to '28.0.0'
