### ISSUE TITLE
Need to upgrade grade version in the repostiory.

### ISSUE THREAD

**Issue by sanketdhole** [udacity/ud851-Sunshine#136]
The grade version in every project must be upgraded as there are problems while running each exercise of the project.

**Comment by DigitalSorceress** [comment]
I've also noticed that most every app also has an invalid MainActivity.java .. showing a "unable to resolve symbol AppCompatActivity" .. Every one I've had to invalidate and restart... and some solutions/exercises
 like the S03-01 just does not want to behave... keeps complaining about unable to resolve.. have tried adding + to 
dependency version etc.. just really being a pain

**Comment by raghukrishnamoorthy** [comment]
@DigitalSorceress Are you saying working through these examples is not gonna be a smooth experience anymore?

**Comment by johnshea** [comment]
Code has been updated with latest Gradle, Android Gradle plugin, and dependencies.
