### ISSUE TITLE
Failed to crunch file

### ISSUE THREAD

**Issue by pankhuriagarwal** [udacity/ud851-Sunshine#14]
All the apps are showing the same error when run. "Failed to crunch file". In this error it says failed to crunch an image file from drawables in exploded-aar into drawables in res folder.

**Comment by codingworkshopru** [comment]
This error may occur when path to some file is too long (more than 255 symbols). Try to move project directory to root (i.e. C:\ on Windows or /home on *nix) and run it again.

**Comment by donMichaelL** [comment]
@codingworkshopru  your solution worked for me

**Comment by pankhuriagarwal** [comment]
Yes . the solution worked.

**Comment by JeremySilverTongue** [comment]
Thanks for the heads up. I had fixed this in the exercise repo, but not here X_x
