### ISSUE TITLE
Actualización a Android studio 3.0

### ISSUE THREAD

**Issue by sandrapw58** [udacity/ud851-Sunshine#153]
Hola, 
actualize a Android Studio 3.0 y cuando compilo me da el siguiente error:
--Can´t find bundle for base name messages.Android.JpsBundle, locale es_ES

Encontre en un foro de aquí, que era añadir en modulo Android-Gradle, pero esto tampoco lo soluciona y empiezan de nuevo a salir errores que no se solucionar.

Alguien con la solución? O como habéis hecho? Os habéis actualizado?

**Comment by johnshea** [comment]
Code has been updated with latest Gradle, Android Gradle plugin, and dependencies.
