### ISSUE TITLE
Exercise s06.03 problem in NetworkUtils

### ISSUE THREAD

**Issue by intkhabahmed** [udacity/ud851-Sunshine#154]
The FORECAST_BASE_URL is set to STATIC_WEATHER_URL, so the weather is not updating for the preferred location.
Please change it to DYNAMIC_WEATHER_URL and also add ToDo for that so that students can change it
![screenshot 3](https://user-images.githubusercontent.com/18560483/36438586-64ea2ff0-1690-11e8-882f-b7a38c317699.png)

**Comment by bskup** [comment]
Either way it's pulling data from their fake weather server and not from the user's preferred location. If you change it to DYNAMIC_WEATHER_URL and then hit Refresh in the Sunshine app repeatedly, it just displays a random array of weather each time you refresh. Udacity needs to change the description on the quiz for that lesson to reflect the fact that even after completing the required TODOs the app will not update weather based on the user's preferred location. However, the option to open location in map does open the user's preferred location properly. That's how you can confirm you're pulling the preferences correctly.

**Comment by intkhabahmed** [comment]
ok
