### ISSUE TITLE
Import Issues

### ISSUE THREAD

**Issue by ghost** [udacity/ud851-Sunshine#159]
Hey whats up i am really new to GitHub i am having issues importing the downloaded zip files into my android studio.I don't really know how to do it.

**Comment by sudachom** [comment]
Hey I did the PDF File to show how to download the zip file and import to the Android Studio. I hope that it helps you. Good luck. 
[GitHub_File_Download.pdf](https://github.com/udacity/ud851-Sunshine/files/1791493/GitHub_File_Download.pdf)

**Comment by johnshea** [comment]
Your issue is related to Android Studio. It is not caused by the repo.
