### ISSUE TITLE
S02.01 Solution not works

### ISSUE THREAD

**Issue by Junjiu** [udacity/ud851-Sunshine#165]
The key error log is the following:
"
04-04 22:12:45.374 7026-7041/? V/NetworkUtils: Built URI https://andfun-weather.udacity.com/staticweather?q=94043%2CUSA&mode=json&units=metric&cnt=14
04-04 22:12:45.378 7026-7041/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
04-04 22:12:45.381 7026-7041/? W/System.err: java.net.UnknownHostException: Unable to resolve host "andfun-weather.udacity.com": No address associated with hostname
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
"
I didn't change anything in the solution. Please helps.

**Comment by tranquangphuc** [comment]
Maybe WI-FI had turned off.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.

**Comment by munawwerali** [comment]
It requires an internet connection to be active on the device.

**Comment by soma2010** [comment]
It still doesn't work in emulator and getting the same error.. Kindly suggest how to make it work in Simulator? Thanks!
java.net.UnknownHostException: Unable to resolve host "andfun-weather.udacity.com": No address associated with hostname
