### ISSUE TITLE
gradle can't find sdk location

### ISSUE THREAD

**Issue by codefusser** [udacity/ud851-Sunshine#175]
Hi,

If I import this project with Android studio running on Mac PC, I get the message that the project already exist, and attempt to use the "open project" option, gradle reports with a message "sdk location not found". The Android studio seems to be working fine because when I create a new project from scratch everything works fine.

Any hint to resolving this issues?

Thanks.

**Comment by codefusser** [comment]
Thought I should send you a screenshot

![screen shot 2018-05-28 at 2 49 26 pm](https://user-images.githubusercontent.com/14119586/40619815-701f59dc-628e-11e8-9f96-0931ab6b4b3d.png)

**Comment by Felixomeki** [comment]
At can be the software your using on mac

We offer a wide variety of services; our primary focus lies in IT
Outsourcing striving to provide SME businesses with exceptional service. We
are Microsoft Partners and thus mainly deal and operate within the
Microsoft circle.Email Us for more Info <felix@arielmc.co.za>

**Comment by codefusser** [comment]
which software are you referring to? OS X: yosemite

**Comment by codefusser** [comment]
Yep! It now works...

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
