### ISSUE TITLE
Compile and AndroidTestCompile are obselete, should be replaced with Implementation and AndroidTestImplementation

### ISSUE THREAD

**Issue by Mikesteinberg** [udacity/ud851-Sunshine#177]
Compile and AndroidTestCompile are obsolete and will be deprecated at the end of the year. Compile should be replaced with implementation and AndroidTestCompile should be replaced with AndroidTestImplementation in the build.gradle(Module:App) file for each project. Thanks

**Comment by Mikesteinberg** [comment]
Another Necessary change is 'com.android.support:appcompat-v7:25.1.0' needs to be replaced with 'com.android.support:appcompat-v7:25.1.+' or it won't work properly.

**Comment by johnshea** [comment]
Code has been updated with latest Gradle, Android Gradle plugin, and dependencies.

These have been resolved.
