### ISSUE TITLE
Grable build error

### ISSUE THREAD

**Issue by ghost** [udacity/ud851-Sunshine#180]
Every time when I open the project I am getting an error that 'failed to create directory C:/...'

**Comment by ghost** [comment]
I think you have to set a pathway for sdk and syncronize the gradle.
Thank you.

**Comment by Ranjan9192** [comment]
1. Go to studio default settings n check repo,SDK  and gradle path n then
compare with physical path if both are same then sync the cradle.

2. Just reimport the project via built.gradle file with an active internet
connection.

**Comment by Ranjan9192** [comment]
If it's .git error then clone the project  via terminal then import into
android studio(locally) after that link the offline repo to actually .git
repo.

**Comment by johnshea** [comment]
This issue does not appear to be an issue with the repo itself.
