### ISSUE TITLE
[S11.02-Solution-TodayListItem] getFriendlyDateString() marks tomorrow with "Today" in error

### ISSUE THREAD

**Issue by tatsuyafujisaki** [udacity/ud851-Sunshine#183]
Hello,

I have found a minor issue in **S11.02-Solution-TodayListItem** on the `student` branch.

Running the project at noon on September 21 in Japan, September 22 is marked with "Today" in error.

![screenshot](https://user-images.githubusercontent.com/1838962/45858205-36172d00-bd97-11e8-93d7-99bce3855868.png)

The error seems to originate from `getFriendlyDateString()` but I'm not 100% sure if the error is caused by time zone difference.

**Comment by tatsuyafujisaki** [comment]
I have found the root cause and the solution.

Inside `getFriendlyDateString(...)`, changing
```java
long localDate = getLocalMidnightFromNormalizedUtcDate(normalizedUtcMidnight);
long daysFromEpochToProvidedDate = elapsedDaysSinceEpoch(localDate);
```
to
```java
long localDate = normalizedUtcMidnight;
long daysFromEpochToProvidedDate = elapsedDaysSinceEpoch(localDate);
```
will solve the problem. This is because `elapsedDaysSinceEpoch(...)` expects a UTC date rather than a local date as follows.
```java
private static long elapsedDaysSinceEpoch(long utcDate) {
    return TimeUnit.MILLISECONDS.toDays(utcDate);
}
```

**Comment by shakesgar** [comment]
Great thanks
