### ISSUE TITLE
obsolete warnings

### ISSUE THREAD

**Issue by aleafonthewind** [udacity/ud851-Sunshine#184]
I am getting the following warnings from the java compiler:

WARNING: Configuration 'compile' is obsolete
WARNING: Configuration 'androidTestCompile' is obsolete 
WARNING: Configuration 'androidTestApi' is obsolete
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored,

Well at least the first tag of the warnings

**Comment by johnshea** [comment]
Code has been updated with latest Gradle, Android Gradle plugin, and dependencies.

These specific warnings have been resolved.
