### ISSUE TITLE
[WINDOWS OS ONLY] Creating new empty activity via "New Android Activity" wizard causes Android Studio IDE errors

### ISSUE THREAD

**Issue by arshcaria** [udacity/ud851-Sunshine#24]
In Windows OS, the build folder is redirected to `C:\tmp\***`. 

```
allprojects {
    String osName = System.getProperty("os.name").toLowerCase();
    if (osName.contains("windows")) {
        buildDir = "C:/tmp/${rootProject.name}/${project.name}"
    }
    repositories {
        jcenter()
    }
}

```
This causes an IDE error when creating new activities using "New Android Activity" wizard. The activity won't be created and the error will be caused by clicking "Finish".

Removing the lines that redirects build folder in the gradle file solves the problem.

This issue is confirmed here as well:
https://code.google.com/p/android/issues/detail?id=232076

Screenshot:
![image 3](https://cloud.githubusercontent.com/assets/3211106/22640226/a9f48c3c-ec8c-11e6-9d3b-e1a5a820aa06.png)

**Comment by mahmuthanb** [comment]
Thank you so much!

**Comment by DroidPulkit** [comment]
One more solution to do is https://stackoverflow.com/a/42947592/4204668

**Comment by Adithya188288** [comment]
Thank You

**Comment by badgerbay** [comment]
I tried other "fixes," but modifying the gradle file:

1)Add the repo reference to google()
2) Remove the buildDir code from the build.gradle file:
     buildDir = "C:/tmp/${rootProject.name}/${project.name}"

....it solved the problem!  Thank you.

**Comment by christian1607** [comment]
Thank you
