### ISSUE TITLE
Lesson 10. NullPointerException?

### ISSUE THREAD

**Issue by codingworkshopru** [udacity/ud851-Sunshine#26]
Can [this](https://github.com/udacity/ud851-Sunshine/blob/student/S10.02-Solution-SmarterSyncing/app/src/main/java/com/example/android/sunshine/sync/SunshineSyncUtils.java#L103)  cause NullPointerException

**Comment by johnshea** [comment]
Closing as this is not an issue related to the repo's code but is a general programming question.
