### ISSUE TITLE
Does not support Gradle Build System.

### ISSUE THREAD

**Issue by Adityareddyp** [udacity/ud851-Sunshine#35]
Hello,

This project is not supported by Gradle Build system,is there a different/updated repositiory I should be following which runs on Gradle Build System ? Please Help.

**Comment by ChiraagCK** [comment]
Are you facing issue with the junit 4.12?

**Comment by Adityareddyp** [comment]
I don't think so,I get a notification directing me to a page on Android Developers,to migrate to gradle build system. Here's the link : https://developer.android.com/studio/intro/migrate.html

**Comment by jwill** [comment]
Every exercise in this repository (ie every top level folder) is its own Gradle project. You should open the project you want to work on and not try to import the whole repository if that's what you are doing.

On that page you linked, search for "Import a Gradle-based IntelliJ project" and follow the instructions.
