### ISSUE TITLE
Its ForecastAdapter.java, not ForecastAdapter.xml

### ISSUE THREAD

**Issue by ghost** [udacity/ud851-Sunshine#4]
https://github.com/udacity/ud851-Sunshine/blob/S03.01-Exercise-RecyclerView/app/src/main/java/com/example/android/sunshine/MainActivity.java

Line 52, 84.

It should be ForecastAdapter.java instead of ForecastAdapter.xml.

**Comment by croworc** [comment]
@subamrana 
Nice catch - found the bug even behind the comment curtain!
:smile:

**Comment by JeremySilverTongue** [comment]
Thanks! Fixed in https://github.com/udacity/ud851-Sunshine/commit/4023a1bc37ac842769ecfa3607cea2a70ded75ca
