### ISSUE TITLE
S09.04 -> TODO 18/34 -> Wrong order

### ISSUE THREAD

**Issue by rsd-raul** [udacity/ud851-Sunshine#40]
This is not really a proper issue, but an ordering problem, the TODO number 18 in MainActivity reads:

`// TODO (18) Call the showLoading method`

While the TODO number 34 reads:

`//  TODO (34) Create a method called showLoading that shows the loading indicator and hides the data`

Creating a minor name/order confusion. As the showLoading method doesn't have any dependency the TODO 34 can be moved to the position 18 and all the other TODO's indexes increased by 1 without problems.

Ps: Not sure if you guys prefer a pull request for such a detail, if so, let me know.

**Comment by gabor-meszaros** [comment]
I agree. I have just wanted to report this issue.

**Comment by jwill** [comment]
PR would be best.

**Comment by intrepidOlivia** [comment]
This issue is still open. Is it up to students to initiate a pull request?

**Comment by jwill** [comment]
Thanks for the interest but I'll be closing this issue.

**Comment by intrepidOlivia** [comment]
Generally throughout the course, the order of the TODOs will have the student write a method before referencing it. Is there any particular reason not to follow that pattern here? It's confusing to be instructed to call a method that doesn't exist yet.
