### ISSUE TITLE
String should be "Share Thoughts" as requested in Udacity exercise

### ISSUE THREAD

**Issue by hinzvc** [udacity/ud851-Sunshine#7]
ud851-Sunshine/S04.03-Solution-AddMapAndSharing/app/src/main/res/values/strings.xml 
line 30 should be
    <string name="action_share">Share Thoughts</string>
as quiz checklist asks
![image](https://cloud.githubusercontent.com/assets/16346546/21666492/e544d51c-d2bf-11e6-8c16-274cd397bc3e.png)

**Comment by technoplato** [comment]
This is actually correct as is. This share action in the app is about sharing the app. The share thoughts video is an artifact of the older version of the course and you should be able to share your thoughts through the Udacity webpage.

**Comment by JeremySilverTongue** [comment]
Removing the first item in the quiz, as we didn't actually include it in the exercise or solution code.
