### ISSUE TITLE
Zip File Unzipping Improperly

### ISSUE THREAD

**Issue by loving1** [udacity/ud851-Sunshine#80]
Not all of the files are working. It could be my comp. Is anyone else having issues with this?

**Comment by jwill** [comment]
@loving1  We don't actively monitor this issue list enough to guarantee timely help. If you are enrolled in the Nanodegree program, I encourage you to consult a mentor. 

If you are enrolled in the free course, you can ask your question in the forums here: https://discussions.udacity.com/c/standalone-courses/developing-android-apps
