### ISSUE TITLE
project opening problem in Android studio 

### ISSUE THREAD

**Issue by waqaramjad** [udacity/ud851-Sunshine#82]
i import project sunshine but it cant be open untill 1 hour waiting . its only building the project but show nothing

**Comment by jwill** [comment]
@waqaramjad We don't actively monitor this issue list enough to guarantee timely help. If you are enrolled in the Nanodegree program, I encourage you to consult a mentor. 

If you are enrolled in the free course, you can ask your question in the forums here: https://discussions.udacity.com/c/standalone-courses/developing-android-apps
