### ISSUE TITLE
S01.01-Exercise-CreateLayout - Wrong TODO definition

### ISSUE THREAD

**Issue by diksito** [udacity/ud851-Sunshine#9]
Hi,

The following TODO action is incorrect or confusing - 

> TODO (2) Change the android:id attribute to tv_weather_data

https://github.com/udacity/ud851-Sunshine/blob/student/S01.01-Exercise-CreateLayout/app/src/main/res/layout/activity_forecast.xml#L28

In the solution project this id is added(not changed) to TextView. As it's written a person may understand that need to change id of FrameLayout as it has id in the exercise.

**Comment by JeremySilverTongue** [comment]
Good call. Fixed in https://github.com/udacity/ud851-Sunshine/commit/e3039674add93237feacc41cc2c3ab695df26a20
